module.exports = /*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */
(function() {
  "use strict";

  function peg$subclass(child, parent) {
    function ctor() { this.constructor = child; }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor();
  }

  function peg$SyntaxError(message, expected, found, location) {
    this.message  = message;
    this.expected = expected;
    this.found    = found;
    this.location = location;
    this.name     = "SyntaxError";

    if (typeof Error.captureStackTrace === "function") {
      Error.captureStackTrace(this, peg$SyntaxError);
    }
  }

  peg$subclass(peg$SyntaxError, Error);

  peg$SyntaxError.buildMessage = function(expected, found) {
    var DESCRIBE_EXPECTATION_FNS = {
          literal: function(expectation) {
            return "\"" + literalEscape(expectation.text) + "\"";
          },

          "class": function(expectation) {
            var escapedParts = "",
                i;

            for (i = 0; i < expectation.parts.length; i++) {
              escapedParts += expectation.parts[i] instanceof Array
                ? classEscape(expectation.parts[i][0]) + "-" + classEscape(expectation.parts[i][1])
                : classEscape(expectation.parts[i]);
            }

            return "[" + (expectation.inverted ? "^" : "") + escapedParts + "]";
          },

          any: function(expectation) {
            return "any character";
          },

          end: function(expectation) {
            return "end of input";
          },

          other: function(expectation) {
            return expectation.description;
          }
        };

    function hex(ch) {
      return ch.charCodeAt(0).toString(16).toUpperCase();
    }

    function literalEscape(s) {
      return s
        .replace(/\\/g, '\\\\')
        .replace(/"/g,  '\\"')
        .replace(/\0/g, '\\0')
        .replace(/\t/g, '\\t')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
        .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
    }

    function classEscape(s) {
      return s
        .replace(/\\/g, '\\\\')
        .replace(/\]/g, '\\]')
        .replace(/\^/g, '\\^')
        .replace(/-/g,  '\\-')
        .replace(/\0/g, '\\0')
        .replace(/\t/g, '\\t')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
        .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
    }

    function describeExpectation(expectation) {
      return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
    }

    function describeExpected(expected) {
      var descriptions = new Array(expected.length),
          i, j;

      for (i = 0; i < expected.length; i++) {
        descriptions[i] = describeExpectation(expected[i]);
      }

      descriptions.sort();

      if (descriptions.length > 0) {
        for (i = 1, j = 1; i < descriptions.length; i++) {
          if (descriptions[i - 1] !== descriptions[i]) {
            descriptions[j] = descriptions[i];
            j++;
          }
        }
        descriptions.length = j;
      }

      switch (descriptions.length) {
        case 1:
          return descriptions[0];

        case 2:
          return descriptions[0] + " or " + descriptions[1];

        default:
          return descriptions.slice(0, -1).join(", ")
            + ", or "
            + descriptions[descriptions.length - 1];
      }
    }

    function describeFound(found) {
      return found ? "\"" + literalEscape(found) + "\"" : "end of input";
    }

    return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found.";
  };

  function peg$parse(input, options) {
    options = options !== void 0 ? options : {};

    var peg$FAILED = {},

        peg$startRuleFunctions = { start: peg$parsestart },
        peg$startRuleFunction  = peg$parsestart,

        peg$c0 = function(p) {return p;},
        peg$c1 = function(s, p) {
          	parsed.sections = addUniqueElements([s], parsed.sections);
            return parsed;
          },
        peg$c2 = function(f, p) {
          	parsed.fields = addUniqueElements([f], parsed.fields);
            return parsed;
          },
        peg$c3 = function(r, p) {
            parsed.rows = addUniqueElements([r], parsed.rows);
            return parsed;
          },
        peg$c4 = function(c, p) {
           	parsed.cols = addUniqueElements([c], parsed.cols);
            return parsed;
          },
        peg$c5 = "",
        peg$c6 = function() { return parsed; },
        peg$c7 = function(n, c) {
                
        		var section = {};
                section.name = n;
                for(var o in c) {
                    section[o] = c[o];
                }

            	return section;
            },
        peg$c8 = "{",
        peg$c9 = peg$literalExpectation("{", false),
        peg$c10 = "}",
        peg$c11 = peg$literalExpectation("}", false),
        peg$c12 = function(i, t, d, r) {
            	return {icon: i, title: t, description: d[0] || null, rows: r[0] || null};
            },
        peg$c13 = "icon",
        peg$c14 = peg$literalExpectation("icon", false),
        peg$c15 = function(fa) {
            	return fa;
            },
        peg$c16 = "title",
        peg$c17 = peg$literalExpectation("title", false),
        peg$c18 = function(t) {
            	return t;
            },
        peg$c19 = "description",
        peg$c20 = peg$literalExpectation("description", false),
        peg$c21 = function(n, c) {
                
                var field = {};
                field.name = n;
        		for(var o in c) {
                    field[o] = c[o];
                }
                return field;
            },
        peg$c22 = function(t) {
            	return {type: t};
            },
        peg$c23 = "type",
        peg$c24 = peg$literalExpectation("type", false),
        peg$c25 = function(t) {
            	return t
            },
        peg$c26 = function(n, c) {
            	var row = {};
                row.name = n;
                for(var o in c) {
                    row[o] = c[o];
                }
                return row;
            },
        peg$c27 = function(c) {
            	return {cols: c[0]};
            },
        peg$c28 = function(n, c) {
            	var col = {}; 
                col.name = n;
             	for(var o in c) {
                    col[o] = c[o];
                }
                return col;
            },
        peg$c29 = function(s, f) {
            	return {size: s, fields: f[0]};
            },
        peg$c30 = "size",
        peg$c31 = peg$literalExpectation("size", false),
        peg$c32 = function(s) {
                return s.join('');    
            },
        peg$c33 = "cols",
        peg$c34 = peg$literalExpectation("cols", false),
        peg$c35 = function(c) {
            	return c[0];
            },
        peg$c36 = "rows",
        peg$c37 = peg$literalExpectation("rows", false),
        peg$c38 = ",",
        peg$c39 = peg$literalExpectation(",", false),
        peg$c40 = function(c, cl) {return addUniqueElements([c], cl);},
        peg$c41 = function(c) {return [c]},
        peg$c42 = "fields",
        peg$c43 = peg$literalExpectation("fields", false),
        peg$c44 = function(f) {
            	return f;
            },
        peg$c45 = function(f, fl) { return addUniqueElements([f], fl);},
        peg$c46 = function(f) { return [f]},
        peg$c47 = function(r, rl) { return addUniqueElements([r], rl);},
        peg$c48 = function(r) { return [r]},
        peg$c49 = "section",
        peg$c50 = peg$literalExpectation("section", false),
        peg$c51 = "field",
        peg$c52 = peg$literalExpectation("field", false),
        peg$c53 = "row",
        peg$c54 = peg$literalExpectation("row", false),
        peg$c55 = "col",
        peg$c56 = peg$literalExpectation("col", false),
        peg$c57 = /^[a-zA-Z.]/,
        peg$c58 = peg$classExpectation([["a", "z"], ["A", "Z"], "."], false, false),
        peg$c59 = /^[A-z0-9.]/,
        peg$c60 = peg$classExpectation([["A", "z"], ["0", "9"], "."], false, false),
        peg$c61 = function(head, tail) { return `${head}${tail.join('')}`; },
        peg$c62 = /^['\n'|'\t'|'\r'|' '|\u2028|\u2029]/,
        peg$c63 = peg$classExpectation(["'", "\n", "'", "|", "'", "\t", "'", "|", "'", "\r", "'", "|", "'", " ", "'", "|", "\u2028", "|", "\u2029"], false, false),
        peg$c64 = /^['\t'|' '|\u2028|\u2029]/,
        peg$c65 = peg$classExpectation(["'", "\t", "'", "|", "'", " ", "'", "|", "\u2028", "|", "\u2029"], false, false),
        peg$c66 = /^[A-Z]/,
        peg$c67 = peg$classExpectation([["A", "Z"]], false, false),
        peg$c68 = /^[A-z0-9]/,
        peg$c69 = peg$classExpectation([["A", "z"], ["0", "9"]], false, false),
        peg$c70 = "textarea",
        peg$c71 = peg$literalExpectation("textarea", false),
        peg$c72 = "input",
        peg$c73 = peg$literalExpectation("input", false),
        peg$c74 = /^[0-9]/,
        peg$c75 = peg$classExpectation([["0", "9"]], false, false),
        peg$c76 = "fa-user",
        peg$c77 = peg$literalExpectation("fa-user", false),
        peg$c78 = "fa-wrench",
        peg$c79 = peg$literalExpectation("fa-wrench", false),

        peg$currPos          = 0,
        peg$savedPos         = 0,
        peg$posDetailsCache  = [{ line: 1, column: 1 }],
        peg$maxFailPos       = 0,
        peg$maxFailExpected  = [],
        peg$silentFails      = 0,

        peg$result;

    if ("startRule" in options) {
      if (!(options.startRule in peg$startRuleFunctions)) {
        throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
      }

      peg$startRuleFunction = peg$startRuleFunctions[options.startRule];
    }

    function text() {
      return input.substring(peg$savedPos, peg$currPos);
    }

    function location() {
      return peg$computeLocation(peg$savedPos, peg$currPos);
    }

    function expected(description, location) {
      location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

      throw peg$buildStructuredError(
        [peg$otherExpectation(description)],
        input.substring(peg$savedPos, peg$currPos),
        location
      );
    }

    function error(message, location) {
      location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

      throw peg$buildSimpleError(message, location);
    }

    function peg$literalExpectation(text, ignoreCase) {
      return { type: "literal", text: text, ignoreCase: ignoreCase };
    }

    function peg$classExpectation(parts, inverted, ignoreCase) {
      return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase };
    }

    function peg$anyExpectation() {
      return { type: "any" };
    }

    function peg$endExpectation() {
      return { type: "end" };
    }

    function peg$otherExpectation(description) {
      return { type: "other", description: description };
    }

    function peg$computePosDetails(pos) {
      var details = peg$posDetailsCache[pos], p;

      if (details) {
        return details;
      } else {
        p = pos - 1;
        while (!peg$posDetailsCache[p]) {
          p--;
        }

        details = peg$posDetailsCache[p];
        details = {
          line:   details.line,
          column: details.column
        };

        while (p < pos) {
          if (input.charCodeAt(p) === 10) {
            details.line++;
            details.column = 1;
          } else {
            details.column++;
          }

          p++;
        }

        peg$posDetailsCache[pos] = details;
        return details;
      }
    }

    function peg$computeLocation(startPos, endPos) {
      var startPosDetails = peg$computePosDetails(startPos),
          endPosDetails   = peg$computePosDetails(endPos);

      return {
        start: {
          offset: startPos,
          line:   startPosDetails.line,
          column: startPosDetails.column
        },
        end: {
          offset: endPos,
          line:   endPosDetails.line,
          column: endPosDetails.column
        }
      };
    }

    function peg$fail(expected) {
      if (peg$currPos < peg$maxFailPos) { return; }

      if (peg$currPos > peg$maxFailPos) {
        peg$maxFailPos = peg$currPos;
        peg$maxFailExpected = [];
      }

      peg$maxFailExpected.push(expected);
    }

    function peg$buildSimpleError(message, location) {
      return new peg$SyntaxError(message, null, null, location);
    }

    function peg$buildStructuredError(expected, found, location) {
      return new peg$SyntaxError(
        peg$SyntaxError.buildMessage(expected, found),
        expected,
        found,
        location
      );
    }

    function peg$parsestart() {
      var s0, s1;

      s0 = peg$currPos;
      s1 = peg$parseprog();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c0(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseprog() {
      var s0, s1, s2, s3, s4;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parsesectionDecl();
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseprog();
            if (s4 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c1(s2, s4);
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = [];
        s2 = peg$parseSPACE();
        while (s2 !== peg$FAILED) {
          s1.push(s2);
          s2 = peg$parseSPACE();
        }
        if (s1 !== peg$FAILED) {
          s2 = peg$parsefieldDecl();
          if (s2 !== peg$FAILED) {
            s3 = [];
            s4 = peg$parseSPACE();
            while (s4 !== peg$FAILED) {
              s3.push(s4);
              s4 = peg$parseSPACE();
            }
            if (s3 !== peg$FAILED) {
              s4 = peg$parseprog();
              if (s4 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c2(s2, s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
        if (s0 === peg$FAILED) {
          s0 = peg$currPos;
          s1 = [];
          s2 = peg$parseSPACE();
          while (s2 !== peg$FAILED) {
            s1.push(s2);
            s2 = peg$parseSPACE();
          }
          if (s1 !== peg$FAILED) {
            s2 = peg$parserowDecl();
            if (s2 !== peg$FAILED) {
              s3 = [];
              s4 = peg$parseSPACE();
              while (s4 !== peg$FAILED) {
                s3.push(s4);
                s4 = peg$parseSPACE();
              }
              if (s3 !== peg$FAILED) {
                s4 = peg$parseprog();
                if (s4 !== peg$FAILED) {
                  peg$savedPos = s0;
                  s1 = peg$c3(s2, s4);
                  s0 = s1;
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
          if (s0 === peg$FAILED) {
            s0 = peg$currPos;
            s1 = [];
            s2 = peg$parseSPACE();
            while (s2 !== peg$FAILED) {
              s1.push(s2);
              s2 = peg$parseSPACE();
            }
            if (s1 !== peg$FAILED) {
              s2 = peg$parsecolDecl();
              if (s2 !== peg$FAILED) {
                s3 = [];
                s4 = peg$parseSPACE();
                while (s4 !== peg$FAILED) {
                  s3.push(s4);
                  s4 = peg$parseSPACE();
                }
                if (s3 !== peg$FAILED) {
                  s4 = peg$parseprog();
                  if (s4 !== peg$FAILED) {
                    peg$savedPos = s0;
                    s1 = peg$c4(s2, s4);
                    s0 = s1;
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
            if (s0 === peg$FAILED) {
              s0 = peg$currPos;
              s1 = peg$c5;
              if (s1 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c6();
              }
              s0 = s1;
            }
          }
        }
      }

      return s0;
    }

    function peg$parsesectionDecl() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSECTION();
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSECTION_NAME();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                s6 = peg$parsesectionConfigDecl();
                if (s6 !== peg$FAILED) {
                  s7 = [];
                  s8 = peg$parseSPACE();
                  while (s8 !== peg$FAILED) {
                    s7.push(s8);
                    s8 = peg$parseSPACE();
                  }
                  if (s7 !== peg$FAILED) {
                    peg$savedPos = s0;
                    s1 = peg$c7(s4, s6);
                    s0 = s1;
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsesectionConfigDecl() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8;

      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 123) {
        s1 = peg$c8;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c9); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseSPACE();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseSPACE();
        }
        if (s2 !== peg$FAILED) {
          s3 = peg$parseiconDecl();
          if (s3 !== peg$FAILED) {
            s4 = peg$parsesectionTitleDecl();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parsesectionDescriptionDecl();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parsesectionDescriptionDecl();
              }
              if (s5 !== peg$FAILED) {
                s6 = [];
                s7 = peg$parserowListDecl();
                while (s7 !== peg$FAILED) {
                  s6.push(s7);
                  s7 = peg$parserowListDecl();
                }
                if (s6 !== peg$FAILED) {
                  s7 = [];
                  s8 = peg$parseSPACE();
                  while (s8 !== peg$FAILED) {
                    s7.push(s8);
                    s8 = peg$parseSPACE();
                  }
                  if (s7 !== peg$FAILED) {
                    if (input.charCodeAt(peg$currPos) === 125) {
                      s8 = peg$c10;
                      peg$currPos++;
                    } else {
                      s8 = peg$FAILED;
                      if (peg$silentFails === 0) { peg$fail(peg$c11); }
                    }
                    if (s8 !== peg$FAILED) {
                      peg$savedPos = s0;
                      s1 = peg$c12(s3, s4, s5, s6);
                      s0 = s1;
                    } else {
                      peg$currPos = s0;
                      s0 = peg$FAILED;
                    }
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseiconDecl() {
      var s0, s1, s2, s3, s4, s5, s6;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 4) === peg$c13) {
          s2 = peg$c13;
          peg$currPos += 4;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c14); }
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseFA_ICON();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c15(s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsesectionTitleDecl() {
      var s0, s1, s2, s3, s4, s5, s6;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 5) === peg$c16) {
          s2 = peg$c16;
          peg$currPos += 5;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c17); }
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseTRANSLATION_KEY();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c18(s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsesectionDescriptionDecl() {
      var s0, s1, s2, s3, s4, s5, s6;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 11) === peg$c19) {
          s2 = peg$c19;
          peg$currPos += 11;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c20); }
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseTRANSLATION_KEY();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c18(s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsefieldDecl() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseFIELD();
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseFIELD_NAME();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                s6 = peg$parsefieldConfigDecl();
                if (s6 !== peg$FAILED) {
                  s7 = [];
                  s8 = peg$parseSPACE();
                  while (s8 !== peg$FAILED) {
                    s7.push(s8);
                    s8 = peg$parseSPACE();
                  }
                  if (s7 !== peg$FAILED) {
                    peg$savedPos = s0;
                    s1 = peg$c21(s4, s6);
                    s0 = s1;
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsefieldConfigDecl() {
      var s0, s1, s2, s3, s4, s5;

      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 123) {
        s1 = peg$c8;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c9); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseSPACE();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseSPACE();
        }
        if (s2 !== peg$FAILED) {
          s3 = peg$parsefieldTypeDecl();
          if (s3 !== peg$FAILED) {
            s4 = [];
            s5 = peg$parseSPACE();
            while (s5 !== peg$FAILED) {
              s4.push(s5);
              s5 = peg$parseSPACE();
            }
            if (s4 !== peg$FAILED) {
              if (input.charCodeAt(peg$currPos) === 125) {
                s5 = peg$c10;
                peg$currPos++;
              } else {
                s5 = peg$FAILED;
                if (peg$silentFails === 0) { peg$fail(peg$c11); }
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c22(s3);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsefieldTypeDecl() {
      var s0, s1, s2, s3, s4, s5, s6;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 4) === peg$c23) {
          s2 = peg$c23;
          peg$currPos += 4;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c24); }
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseFIELD_TYPE();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c25(s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parserowDecl() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseROW();
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseROW_NAME();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                s6 = peg$parserowSpecDecl();
                if (s6 !== peg$FAILED) {
                  s7 = [];
                  s8 = peg$parseSPACE();
                  while (s8 !== peg$FAILED) {
                    s7.push(s8);
                    s8 = peg$parseSPACE();
                  }
                  if (s7 !== peg$FAILED) {
                    peg$savedPos = s0;
                    s1 = peg$c26(s4, s6);
                    s0 = s1;
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parserowSpecDecl() {
      var s0, s1, s2, s3, s4, s5;

      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 123) {
        s1 = peg$c8;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c9); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseSPACE();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseSPACE();
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parsecolListDecl();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parsecolListDecl();
          }
          if (s3 !== peg$FAILED) {
            s4 = [];
            s5 = peg$parseSPACE();
            while (s5 !== peg$FAILED) {
              s4.push(s5);
              s5 = peg$parseSPACE();
            }
            if (s4 !== peg$FAILED) {
              if (input.charCodeAt(peg$currPos) === 125) {
                s5 = peg$c10;
                peg$currPos++;
              } else {
                s5 = peg$FAILED;
                if (peg$silentFails === 0) { peg$fail(peg$c11); }
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c27(s3);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsecolDecl() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseCOL();
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseCOL_NAME();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                s6 = peg$parsecolSpecDecl();
                if (s6 !== peg$FAILED) {
                  s7 = [];
                  s8 = peg$parseSPACE();
                  while (s8 !== peg$FAILED) {
                    s7.push(s8);
                    s8 = peg$parseSPACE();
                  }
                  if (s7 !== peg$FAILED) {
                    peg$savedPos = s0;
                    s1 = peg$c28(s4, s6);
                    s0 = s1;
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsecolSpecDecl() {
      var s0, s1, s2, s3, s4, s5;

      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 123) {
        s1 = peg$c8;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c9); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseSPACE();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseSPACE();
        }
        if (s2 !== peg$FAILED) {
          s3 = peg$parsesizeDecl();
          if (s3 !== peg$FAILED) {
            s4 = peg$parsefieldListDecl();
            if (s4 !== peg$FAILED) {
              if (input.charCodeAt(peg$currPos) === 125) {
                s5 = peg$c10;
                peg$currPos++;
              } else {
                s5 = peg$FAILED;
                if (peg$silentFails === 0) { peg$fail(peg$c11); }
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c29(s3, s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsesizeDecl() {
      var s0, s1, s2, s3, s4, s5, s6;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 4) === peg$c30) {
          s2 = peg$c30;
          peg$currPos += 4;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c31); }
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE_WITHOUT_NEWLINE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE_WITHOUT_NEWLINE();
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSIZE_VALUES();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c32(s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsecolListDecl() {
      var s0, s1, s2, s3, s4, s5, s6;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 4) === peg$c33) {
          s2 = peg$c33;
          peg$currPos += 4;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c34); }
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE_WITHOUT_NEWLINE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE_WITHOUT_NEWLINE();
          }
          if (s3 !== peg$FAILED) {
            s4 = [];
            s5 = peg$parsecolNameListDecl();
            if (s5 !== peg$FAILED) {
              while (s5 !== peg$FAILED) {
                s4.push(s5);
                s5 = peg$parsecolNameListDecl();
              }
            } else {
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c35(s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parserowListDecl() {
      var s0, s1, s2, s3, s4, s5, s6;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 4) === peg$c36) {
          s2 = peg$c36;
          peg$currPos += 4;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c37); }
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE_WITHOUT_NEWLINE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE_WITHOUT_NEWLINE();
          }
          if (s3 !== peg$FAILED) {
            s4 = [];
            s5 = peg$parserowNameListDecl();
            if (s5 !== peg$FAILED) {
              while (s5 !== peg$FAILED) {
                s4.push(s5);
                s5 = peg$parserowNameListDecl();
              }
            } else {
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c35(s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsecolNameListDecl() {
      var s0, s1, s2, s3, s4, s5;

      s0 = peg$currPos;
      s1 = peg$parseCOL_NAME();
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseSPACE_WITHOUT_NEWLINE();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseSPACE_WITHOUT_NEWLINE();
        }
        if (s2 !== peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 44) {
            s3 = peg$c38;
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c39); }
          }
          if (s3 !== peg$FAILED) {
            s4 = [];
            s5 = peg$parseSPACE_WITHOUT_NEWLINE();
            while (s5 !== peg$FAILED) {
              s4.push(s5);
              s5 = peg$parseSPACE_WITHOUT_NEWLINE();
            }
            if (s4 !== peg$FAILED) {
              s5 = peg$parsecolNameListDecl();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c40(s1, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$parseCOL_NAME();
        if (s1 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c41(s1);
        }
        s0 = s1;
      }

      return s0;
    }

    function peg$parsefieldListDecl() {
      var s0, s1, s2, s3, s4, s5, s6;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseSPACE();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseSPACE();
      }
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 6) === peg$c42) {
          s2 = peg$c42;
          peg$currPos += 6;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c43); }
        }
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseSPACE_WITHOUT_NEWLINE();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseSPACE_WITHOUT_NEWLINE();
          }
          if (s3 !== peg$FAILED) {
            s4 = [];
            s5 = peg$parsefieldNameListDecl();
            if (s5 !== peg$FAILED) {
              while (s5 !== peg$FAILED) {
                s4.push(s5);
                s5 = peg$parsefieldNameListDecl();
              }
            } else {
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$parseSPACE();
              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$parseSPACE();
              }
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c44(s4);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsefieldNameListDecl() {
      var s0, s1, s2, s3, s4, s5;

      s0 = peg$currPos;
      s1 = peg$parseFIELD_NAME();
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseSPACE_WITHOUT_NEWLINE();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseSPACE_WITHOUT_NEWLINE();
        }
        if (s2 !== peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 44) {
            s3 = peg$c38;
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c39); }
          }
          if (s3 !== peg$FAILED) {
            s4 = [];
            s5 = peg$parseSPACE_WITHOUT_NEWLINE();
            if (s5 !== peg$FAILED) {
              while (s5 !== peg$FAILED) {
                s4.push(s5);
                s5 = peg$parseSPACE_WITHOUT_NEWLINE();
              }
            } else {
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s5 = peg$parsefieldNameListDecl();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c45(s1, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$parseFIELD_NAME();
        if (s1 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c46(s1);
        }
        s0 = s1;
      }

      return s0;
    }

    function peg$parserowNameListDecl() {
      var s0, s1, s2, s3, s4, s5;

      s0 = peg$currPos;
      s1 = peg$parseFIELD_NAME();
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseSPACE_WITHOUT_NEWLINE();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseSPACE_WITHOUT_NEWLINE();
        }
        if (s2 !== peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 44) {
            s3 = peg$c38;
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c39); }
          }
          if (s3 !== peg$FAILED) {
            s4 = [];
            s5 = peg$parseSPACE_WITHOUT_NEWLINE();
            if (s5 !== peg$FAILED) {
              while (s5 !== peg$FAILED) {
                s4.push(s5);
                s5 = peg$parseSPACE_WITHOUT_NEWLINE();
              }
            } else {
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s5 = peg$parserowNameListDecl();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c47(s1, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$parseFIELD_NAME();
        if (s1 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c48(s1);
        }
        s0 = s1;
      }

      return s0;
    }

    function peg$parseSECTION() {
      var s0;

      if (input.substr(peg$currPos, 7) === peg$c49) {
        s0 = peg$c49;
        peg$currPos += 7;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c50); }
      }

      return s0;
    }

    function peg$parseFIELD() {
      var s0;

      if (input.substr(peg$currPos, 5) === peg$c51) {
        s0 = peg$c51;
        peg$currPos += 5;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c52); }
      }

      return s0;
    }

    function peg$parseROW() {
      var s0;

      if (input.substr(peg$currPos, 3) === peg$c53) {
        s0 = peg$c53;
        peg$currPos += 3;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c54); }
      }

      return s0;
    }

    function peg$parseCOL() {
      var s0;

      if (input.substr(peg$currPos, 3) === peg$c55) {
        s0 = peg$c55;
        peg$currPos += 3;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c56); }
      }

      return s0;
    }

    function peg$parseTRANSLATION_KEY() {
      var s0, s1, s2, s3;

      s0 = peg$currPos;
      if (peg$c57.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c58); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c59.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c60); }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c59.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c60); }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c61(s1, s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseSPACE() {
      var s0;

      if (peg$c62.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c63); }
      }

      return s0;
    }

    function peg$parseSPACE_WITHOUT_NEWLINE() {
      var s0;

      if (peg$c64.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c65); }
      }

      return s0;
    }

    function peg$parseSECTION_NAME() {
      var s0, s1, s2, s3;

      s0 = peg$currPos;
      if (peg$c66.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c67); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c68.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c69); }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c68.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c69); }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c61(s1, s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseFIELD_NAME() {
      var s0, s1, s2, s3;

      s0 = peg$currPos;
      if (peg$c66.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c67); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c68.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c69); }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c68.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c69); }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c61(s1, s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseROW_NAME() {
      var s0, s1, s2, s3;

      s0 = peg$currPos;
      if (peg$c66.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c67); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c68.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c69); }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c68.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c69); }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c61(s1, s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseCOL_NAME() {
      var s0, s1, s2, s3;

      s0 = peg$currPos;
      if (peg$c66.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c67); }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c68.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c69); }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c68.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c69); }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c61(s1, s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseFIELD_TYPE() {
      var s0;

      if (input.substr(peg$currPos, 8) === peg$c70) {
        s0 = peg$c70;
        peg$currPos += 8;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c71); }
      }
      if (s0 === peg$FAILED) {
        if (input.substr(peg$currPos, 5) === peg$c72) {
          s0 = peg$c72;
          peg$currPos += 5;
        } else {
          s0 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c73); }
        }
      }

      return s0;
    }

    function peg$parseSIZE_VALUES() {
      var s0, s1;

      s0 = [];
      if (peg$c74.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c75); }
      }
      if (s1 !== peg$FAILED) {
        while (s1 !== peg$FAILED) {
          s0.push(s1);
          if (peg$c74.test(input.charAt(peg$currPos))) {
            s1 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s1 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c75); }
          }
        }
      } else {
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseFA_ICON() {
      var s0;

      s0 = peg$parseFA_USER();
      if (s0 === peg$FAILED) {
        s0 = peg$parseFA_WRENCH();
      }

      return s0;
    }

    function peg$parseFA_USER() {
      var s0;

      if (input.substr(peg$currPos, 7) === peg$c76) {
        s0 = peg$c76;
        peg$currPos += 7;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c77); }
      }

      return s0;
    }

    function peg$parseFA_WRENCH() {
      var s0;

      if (input.substr(peg$currPos, 9) === peg$c78) {
        s0 = peg$c78;
        peg$currPos += 9;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c79); }
      }

      return s0;
    }


      function addUniqueElements(array1, array2) {
        if (array2) {
          for (let i = 0; i < array2.length; i++) {
            if (array1.indexOf(array2[i]) === -1) {
              array1.push(array2[i]);
            }
          }
        }
        return array1;
      }

      function flattenArray(array) {
        var newArray = [];
        for (let i = 0; i < array.length; i ++) {
          if (!array[i].length) {
            newArray.push(array[i]);
          } else {
            for (let j = 0; j < array[i].length; j++) {
              newArray.push(array[i][j]);
            }
          }
        }
        return newArray;
      }

      function addCardinalityToRelationships(cardinality, relationships) {
        if (!relationships) {
          return;
        }
        for (let i = 0; i < relationships.length; i++) {
          relationships[i].cardinality = cardinality;
        }
      }

      const parsed = {
        sections: {}
      };


    peg$result = peg$startRuleFunction();

    if (peg$result !== peg$FAILED && peg$currPos === input.length) {
      return peg$result;
    } else {
      if (peg$result !== peg$FAILED && peg$currPos < input.length) {
        peg$fail(peg$endExpectation());
      }

      throw peg$buildStructuredError(
        peg$maxFailExpected,
        peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
        peg$maxFailPos < input.length
          ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
          : peg$computeLocation(peg$maxFailPos, peg$maxFailPos)
      );
    }
  }

  return {
    SyntaxError: peg$SyntaxError,
    parse:       peg$parse
  };
})();
